[package]
name = "tmd"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "gzip", "socks", "stream"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0" }
sysproxy = "0.3"
futures = "0.3"
